FROM golang:1.26-alpine

RUN apk add --no-cache git tzdata bash curl

RUN go install github.com/air-verse/air@latest

RUN mkdir -p /app
WORKDIR /app

COPY . ./

EXPOSE 8080

CMD sh -c 'air -c "$AIR_CONFIG_PATH"'
