// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: banking.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByNumberRequest) Reset() {
	*x = GetAccountByNumberRequest{}
	mi := &file_banking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByNumberRequest) ProtoMessage() {}

func (x *GetAccountByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByNumberRequest) Descriptor() ([]byte, []int) {
	return file_banking_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByNumberRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetAccountByNumberResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber    string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	ClientId         uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AccountType      string                 `protobuf:"bytes,3,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CurrencyCode     string                 `protobuf:"bytes,4,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,5,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAccountByNumberResponse) Reset() {
	*x = GetAccountByNumberResponse{}
	mi := &file_banking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByNumberResponse) ProtoMessage() {}

func (x *GetAccountByNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByNumberResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByNumberResponse) Descriptor() ([]byte, []int) {
	return file_banking_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByNumberResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *GetAccountByNumberResponse) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetAccountByNumberResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *GetAccountByNumberResponse) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *GetAccountByNumberResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

var File_banking_proto protoreflect.FileDescriptor

const file_banking_proto_rawDesc = "" +
	"\n" +
	"\rbanking.proto\x12\n" +
	"banking.v1\"B\n" +
	"\x19GetAccountByNumberRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"\xd5\x01\n" +
	"\x1aGetAccountByNumberResponse\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12!\n" +
	"\faccount_type\x18\x03 \x01(\tR\vaccountType\x12#\n" +
	"\rcurrency_code\x18\x04 \x01(\tR\fcurrencyCode\x12+\n" +
	"\x11available_balance\x18\x05 \x01(\x01R\x10availableBalance2u\n" +
	"\x0eBankingService\x12c\n" +
	"\x12GetAccountByNumber\x12%.banking.v1.GetAccountByNumberRequest\x1a&.banking.v1.GetAccountByNumberResponseB\x12Z\x10common/pkg/pb;pbb\x06proto3"

var (
	file_banking_proto_rawDescOnce sync.Once
	file_banking_proto_rawDescData []byte
)

func file_banking_proto_rawDescGZIP() []byte {
	file_banking_proto_rawDescOnce.Do(func() {
		file_banking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banking_proto_rawDesc), len(file_banking_proto_rawDesc)))
	})
	return file_banking_proto_rawDescData
}

var file_banking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_banking_proto_goTypes = []any{
	(*GetAccountByNumberRequest)(nil),  // 0: banking.v1.GetAccountByNumberRequest
	(*GetAccountByNumberResponse)(nil), // 1: banking.v1.GetAccountByNumberResponse
}
var file_banking_proto_depIdxs = []int32{
	0, // 0: banking.v1.BankingService.GetAccountByNumber:input_type -> banking.v1.GetAccountByNumberRequest
	1, // 1: banking.v1.BankingService.GetAccountByNumber:output_type -> banking.v1.GetAccountByNumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_banking_proto_init() }
func file_banking_proto_init() {
	if File_banking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banking_proto_rawDesc), len(file_banking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banking_proto_goTypes,
		DependencyIndexes: file_banking_proto_depIdxs,
		MessageInfos:      file_banking_proto_msgTypes,
	}.Build()
	File_banking_proto = out.File
	file_banking_proto_goTypes = nil
	file_banking_proto_depIdxs = nil
}
